name = "«dataflow-rewriter»"
defaultTargets = ["DataflowRewriter"]

[leanOptions]
autoImplicit = false
linter.all = false
weak.linter.refine = false
weak.linter.haveLet = 0
weak.linter.oldObtain = false
weak.linter.hashCommand = false
weak.linter.docPrime = false
weak.linter.style.cdot = false
weak.linter.style.dollarSyntax = false
weak.linter.style.lambdaSyntax = false
weak.aesop.warn.applyIff = false

[[require]]
name = "leanses"
git = "https://github.com/VCA-EPFL/leanses"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "nightly-testing-2025-04-21"

[[lean_lib]]
name = "DataflowRewriter"

[[lean_lib]]
name = "DataflowRewriterTest"

[[lean_exe]]
name = "«dataflow-rewriter»"
root = "Main"
