name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
      - name: verify `lake exe dataflow-rewriter -h` works
        run: |
          lake exe dataflow-rewriter -h
      - name: install `rust` for the oracle
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: installing oracle for graphiti
        run: |
          cargo install --git https://github.com/VCA-EPFL/OracleGraphiti --locked
      - name: test example
        run: |
          lake exe dataflow-rewriter benchmarks/type-correct/preprocessed-baseline-matvec.dot -o out.dot -l out.json --oracle graphiti_oracle
